UsuariosRegistroBundle_homepage:
    pattern:  /index
    defaults: { _controller: UsuariosRegistroBundle:Default:index }
    
registro:
    pattern:  /registro/
    defaults: { _controller: UsuariosRegistroBundle:Default:registro }    
