parameters:
#    usuarios_registro.example.class: Usuarios\RegistroBundle\Example

services:
#    usuarios_registro.example:
#        class: %usuarios_registro.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
