parameters:
#    usuarios_login.example.class: Usuarios\LoginBundle\Example

services:
#    usuarios_login.example:
#        class: %usuarios_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
